// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: greetings.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreetingsService_Greeting_FullMethodName = "/com.nagaraj.projects.grpc.GreetingsService/Greeting"
)

// GreetingsServiceClient is the client API for GreetingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetingsServiceClient interface {
	Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
}

type greetingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetingsServiceClient(cc grpc.ClientConnInterface) GreetingsServiceClient {
	return &greetingsServiceClient{cc}
}

func (c *greetingsServiceClient) Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, GreetingsService_Greeting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetingsServiceServer is the server API for GreetingsService service.
// All implementations must embed UnimplementedGreetingsServiceServer
// for forward compatibility.
type GreetingsServiceServer interface {
	Greeting(context.Context, *GreetingRequest) (*GreetingResponse, error)
	mustEmbedUnimplementedGreetingsServiceServer()
}

// UnimplementedGreetingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreetingsServiceServer struct{}

func (UnimplementedGreetingsServiceServer) Greeting(context.Context, *GreetingRequest) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greeting not implemented")
}
func (UnimplementedGreetingsServiceServer) mustEmbedUnimplementedGreetingsServiceServer() {}
func (UnimplementedGreetingsServiceServer) testEmbeddedByValue()                          {}

// UnsafeGreetingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetingsServiceServer will
// result in compilation errors.
type UnsafeGreetingsServiceServer interface {
	mustEmbedUnimplementedGreetingsServiceServer()
}

func RegisterGreetingsServiceServer(s grpc.ServiceRegistrar, srv GreetingsServiceServer) {
	// If the following call pancis, it indicates UnimplementedGreetingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreetingsService_ServiceDesc, srv)
}

func _GreetingsService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingsServiceServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetingsService_Greeting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingsServiceServer).Greeting(ctx, req.(*GreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GreetingsService_ServiceDesc is the grpc.ServiceDesc for GreetingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.nagaraj.projects.grpc.GreetingsService",
	HandlerType: (*GreetingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _GreetingsService_Greeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greetings.proto",
}
